# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_complete_slider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeimageslide',
            name='hidden_on_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='completevideoslide',
            name='hidden_on_mobile',
            field=models.BooleanField(default=False),
        ),
    ]
